In [43]:
# import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use('fivethirtyeight')



In [44]:
#!pip install joblib

In [50]:
class Perceptron:
  def __init__(self, eta: float=None,epochs:int=None):
    self.weights = np.random.randn(3)*1e-4
    self.eta = eta #learning rate
    self.epochs = epochs #iterations

  def _z_outcome(self, inputs, weights):
    return np.dot(inputs, weights)

  def activation_function(self, z):
    return np.where(z > 0, 1, 0)

  def fit(self, X, Y):
    self.X = X
    self.Y = Y
    X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
    print(f"X_with_bias : \n{X_with_bias}")


    for epoch in range(self.epochs):
      z = self._z_outcome(X_with_bias, self.weights)
      y_hat = self.activation_function(z)
      self.error = self.Y - y_hat
      self.weights = self.weights + self.eta*np.dot(X_with_bias.T, self.error)

    
  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(X),1))]
    z = self._z_outcome(X_with_bias, self.weights)
    return self.activation_function(z)

In [51]:
OR = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}


df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [52]:
def prepare_data(df, target_col = "y"):
  X = df.drop(target_col, axis=1)
  y = df[target_col]

  return X, y

In [53]:
X, y = prepare_data(df_OR)
ETA = 0.1
EPOCHS = 10

model_OR = Perceptron(eta=ETA, epochs=EPOCHS)

In [56]:
model_OR.fit(X, y)
model_OR.predict(X)

X_with_bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]


array([0, 1, 1, 1])